/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_monikawojtasik_setupopencbv_NativeClass */

#ifndef _Included_com_example_monikawojtasik_setupopencbv_NativeClass
#define _Included_com_example_monikawojtasik_setupopencbv_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_monikawojtasik_setupopencbv_NativeClass
 * Method:    findInscribedCircleJNI
 * Signature: (JDDDD[D[DJ)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_monikawojtasik_setupopencbv_NativeClass_findInscribedCircleJNI
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdouble, jdouble, jdoubleArray, jdoubleArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
